spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:mariadb://localhost:3306/yokka
    username: yokka
    password: yokkapass
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: create
    show-sql: true
  messages:
    basename: validation
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 20MB
      max-request-size: 25MB
file:
  upload-dir: ./uploads
nlp:
  train: false
#server:
#  port: 8443
#  ssl:
#    key-store: keystore.p12
#    key-store-password: polipoli123
#    key-store-type: PKCS12
#    key-alias: tomcat