spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test;DB_CLOSE_DELAY=- 1;DB_CLOSE_ON_EXIT=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  messages:
    basename: validation
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 20MB
      max-request-size: 25MB
file:
  upload-dir: ./uploads
nlp:
  train: false