spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oafw0ctj7ArMUGzv0h7
            client-secret: C5PkxaKIYg2s7x-FNMgNfNxCbC86Yw3YkysEN_0F
            scope: openid email profile
        provider:
          okta:
            issuer-uri: https://dev-637006.oktapreview.com/oauth2/default
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  data:
    rest:
      base-path: /api