spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:mariadb://localhost:3306/yokka
    username: root
    password: polipoli123
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  messages:
    basename: validation
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 20MB
      max-request-size: 25MB